title: Paul Przyborski

logo: paul.png

description: Application Developer, Scrum Master, Amateur Bassist, Even More Amateur Race Car Driver

theme: jekyll-theme-minimal

show_downloads: true

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: paul.przyborski@gmail.com